### ISSUE TITLE
Whether readyToExpose is still effective in STT to control delaying TLB lookup?

### ISSUE THREAD

**Issue by morning21** [cwfletcher/stt#7]
I'm reading the implementation about how to control delaying TLB lookup. According to current implementation, STT does not use readyToExpose in InvisiSpec anymore before TLB lookup. That's to say, the status of `isSPEC()` in request is not set if the `isInvisibleSpec` flag is not enabled. Then, the TLB lookup is not delayed.

If I want to enable delaying TLB lookup, is it necessary to enable the `isInvisibleSpec` flag during simulation?

Waiting for your response. Thank you very much!

**Comment by jiyongyu** [comment]
Yes.
https://github.com/cwfletcher/stt/blob/master/src/cpu/o3/iew_impl.hh#L1260
Loads cannot be issued (certainly not be able to perform TLB lookups) if "fenceDelay" is set.

**Comment by morning21** [comment]
I see. Thank you very much!

**Comment by morning21** [comment]
Current STT delays execution for fence delayed loads, instead of handling them with InvisiSpec.
